<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\RewardPoints\Block\Product\View\Earning */
$canShow = true;
if (!$block->isAjax()): ?>
    <?php $canShow = false ?>
    <div data-aw-reward-points-block-name="<?php /* @noEscape */ echo $block->getNameInLayout() ?>"></div>
<?php endif; ?>

<?php if ($canShow && $block->isDisplayBlock()) : ?>
    <div class="product-reward-points-earning">
        <?php /* @noEscape */ echo $block->getPromoText()?>
    </div>
<?php endif; ?>
