<span class="ls-contact-number ls-store-details"><a style="color:#ffffff;margin:10px;font-size:13px;" href="tel:732-510-1415">732-510-1415</a></span>
<span class="demo-tooltip ls-store-details">
	<a href="#" class="tooltip-toggle" style="color:#ffffff;font-size:13px;">Support Mon-Fri 9AM - 5PM</a>
	<span class="tooltip-content">
		<strong style="font-size:15px;color:#444444;margin-bottom:10px!important;">Sales Hours</strong>
        <p style="margin-top:10px;text-transform:none!important"><strong>Mon-Fri : 9AM - 5PM</strong></p>
        <!-- <p style="margin-top:10px;text-transform:none!important"><strong>Sat : 12pm - 5pm</strong></p> -->
		<strong style="font-size:15px;color:#444444;margin-bottom:10px!important;">Customer Service</strong>
		<p style="margin-top:10px;text-transform:none!important"><strong>Mon-Fri : 9AM - 5PM</strong></p>
	</span>
</span>