<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\RewardPoints\Block\Adminhtml\Sales\Order\Create\Payment */
?>
<?php if ($block->canShow()): ?>
    <div class="admin__field admin__field-option">
        <input id="p_method_aw_use_reward_points"
               class="admin__control-checkbox"
               name="payment[aw_use_reward_points]"
               type="checkbox"
               title="<?php echo $block->escapeHtml(__('Reward Points')) ?>"
               value="1"
            <?php /* @noEscape */ echo $block->isUseAwRewardPoints() ? 'checked="checked"' : '' ?> />
        <label class="admin__field-label" for="p_method_aw_use_reward_points">
            <?php /* @noEscape */ echo __('Use Reward Points (%1 available)', $block->formatPrice($block->getBalance())) ?>
        </label>
    </div>
    <script>
        require(['prototype'], function(){
            toggleUseAwRewardPoints = function()
            {
                var data = {};

                data['payment[aw_use_reward_points]'] = ($('p_method_aw_use_reward_points').checked ? 1 : 0);
                order.loadArea(['totals', 'billing_method'], true, data);
            }
            Event.observe($('p_method_aw_use_reward_points'), 'change', toggleUseAwRewardPoints);
            Event.observe(window, 'load', toggleUseAwRewardPoints);
        });
    </script>
<?php endif; ?>
