<?php
/**
 * Unirgy LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.unirgy.com/LICENSE-M1.txt
 *
 * @category   Unirgy
 * @package    Unirgy_DropshipPo
 * @copyright  Copyright (c) 2008-2009 Unirgy LLC (http://www.unirgy.com)
 * @license    http:///www.unirgy.com/LICENSE-M1.txt
 */
?>
<?php $hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data') ?>
<?php $_item = $this->getItem() ?>
<?php $_oItem = $_item->getOrderItem() ?>
<tr class="border" id="udpo_item_<?php echo$_item->getId()?>">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td class="po-item-vendor"><?php echo \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipPo\Helper\Data')->getOrderItemVendorName($_item) ?></td>
    <td class="udpo_item_cost a-center" nowrap="true">
        <input style="width: 100px;" type="text" class="input-text qty-input" name="udpo[costs][<?php echo $_item->getId() ?>]" value="<?php echo $_item->getBaseCost()*1 ?>" onchange="udpoRecalcCosts(this)" />
    </td>
    <td class="udpo_item_qty"><?php echo $_item->getQty()*1 ?></td>
    <td class="udpo_item_rowcost last a-right" alt="<?php echo $_item->getBaseCost()*$_item->getQty() ?>"><?php echo $hlp->displayPrices($this->getOrder(), $_item->getBaseCost()*$_item->getQty()) ?></td>
</tr>

<script type="text/javascript">
//<![CDATA[

require(["jquery", "prototype"], function(jQuery) {
//]]>

});
</script>
