<?php
// no notice of license for now
?>

<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see \Magento\Framework\Block\Html\Calendar
 */
?>

<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {

//<![CDATA[
enUS = <?php echo $enUS?>; // en_US locale reference
Calendar._DN = <?php echo $days['wide']?>; // full day names
Calendar._SDN = <?php echo $days['abbreviated']?>; // short day names
Calendar._FD = <?php echo $firstDay?>; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = <?php echo $months['wide']?>; // full month names
Calendar._SMN = <?php echo $months['abbreviated']?>; // short month names
Calendar._am = <?php echo $am ?>; // am/pm
Calendar._pm = <?php echo $pm ?>;

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "<?php echo __('About the calendar');?>";

Calendar._TT["ABOUT"] =
"<?php echo __('DHTML Date/Time Selector')?>\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"<?php echo __('For latest version visit: %1', 'http://www.dynarch.com/projects/calendar/')?>\n" +
"<?php echo __('Distributed under GNU LGPL. See %1 for details.', 'http://gnu.org/licenses/lgpl.html')?>" +
"\n\n" +
"<?php echo __('Date selection:')?>\n" +
"<?php echo __('- Use the %1, %2 buttons to select year', '\\xab', '\xbb')?>\n" +
"<?php echo __('- Use the %1 buttons to select month', '" + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + "')?>\n" +
"<?php echo __('- Hold mouse button on any of the above buttons for faster selection.')?>";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"<?php echo __('Time selection:')?>\n" +
"<?php echo __('- Click on any of the time parts to increase it')?>\n" +
"<?php echo __('- or Shift-click to decrease it')?>\n" +
"<?php echo __('- or click and drag for faster selection.')?>";

Calendar._TT["PREV_YEAR"] = "<?php echo __('Prev. year (hold for menu)');?>";
Calendar._TT["PREV_MONTH"] = "<?php echo __('Prev. month (hold for menu)');?>";
Calendar._TT["GO_TODAY"] = "<?php echo __('Go Today');?>";
Calendar._TT["NEXT_MONTH"] = "<?php echo __('Next month (hold for menu)');?>";
Calendar._TT["NEXT_YEAR"] = "<?php echo __('Next year (hold for menu)');?>";
Calendar._TT["SEL_DATE"] = "<?php echo __('Select date');?>";
Calendar._TT["DRAG_TO_MOVE"] = "<?php echo __('Drag to move');?>";
Calendar._TT["PART_TODAY"] = ' (' + <?php echo $today ?> + ')';

// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "<?php echo __('Display %1 first', '%s');?>";

// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = <?php echo $weekendDays?>;

Calendar._TT["CLOSE"] = "<?php echo __('Close');?>";
Calendar._TT["TODAY"] = <?php echo $today ?>;
Calendar._TT["TIME_PART"] = "<?php echo __('(Shift-)Click or drag to change value');?>";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = <?php echo $defaultFormat?>;
Calendar._TT["TT_DATE_FORMAT"] = <?php echo $toolTipFormat?>;

Calendar._TT["WK"] = <?php echo $week ?>;
Calendar._TT["TIME"] = "<?php echo __('Time:');?>";
//]]>

});
</script>
