<span class="ls-contact-number ls-store-details"><a style="color:#ffffff;margin:10px;font-size:13px;" href="tel:732-372-4065">732-372-4065</a></span>
<span class="demo-tooltip ls-store-details">
	<a href="#" class="tooltip-toggle" style="color:#ffffff;font-size:13px;">Support Mon-Fri 10 am to 5 pm</a>
	<span class="tooltip-content">
		<strong style="font-size:15px;color:#444444;margin-bottom:10px!important;">NJ Showroom Hours</strong>
        <p style="margin-top:10px;text-transform:none!important"><strong>Mon-Fri : 12pm - 7pm</strong></p>
        <p style="margin-top:10px;text-transform:none!important"><strong>Sat : 12pm - 5pm</strong></p>
		<strong style="font-size:15px;color:#444444;margin-bottom:10px!important;">Online Order Support</strong>
		<p style="margin-top:10px;text-transform:none!important"><strong>Mon-Fri : 10am - 5pm</strong></p>
	</span>
</span>