<?php
/**
 * Unirgy LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.unirgy.com/LICENSE-M1.txt
 *
 * @category   Unirgy
 * @package    Unirgy_DropshipPo
 * @copyright  Copyright (c) 2008-2009 Unirgy LLC (http://www.unirgy.com)
 * @license    http:///www.unirgy.com/LICENSE-M1.txt
 */
?>
<?php
/** @var \Unirgy\Dropship\Helper\Data $hlp */
$hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
/** @var \Magento\Framework\AuthorizationInterface $auth */
$auth = $hlp->getObj('\Magento\Framework\AuthorizationInterface');
$isEditCosts = $hlp->getScopeFlag('udropship/purchase_order/create_po_allow_change_costs') && $auth->isAllowed('Unirgy_DropshipPo::action_edit_cost');
$isViewCost = $auth->isAllowed('Unirgy_DropshipPo::action_view_cost');
$qtyLast = !$isViewCost ? 'last' : '';
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td id="po-item-vendor-<?php echo $_item->getId()?>" class="po-item-vendor"><?php echo $hlp->udpoHlp()->getOrderItemVendorName($_item) ?></td>
    <?php if ($isViewCost): ?>
    <?php if ($isEditCosts): ?>
    <td nowrap="true" id="po-item-cost-<?php echo $_item->getId()?>" class="a-center po-item-cost">
        <input style="width: 100px;" type="text" class="input-text qty-input" name="udpo[costs][<?php echo $_item->getId() ?>]" value="<?php echo $_item->getUdpoBaseCost()*1 ?>" alt="<?php echo $_item->getUdpoOrigBaseCost()*1 ?>" <?php if (!$_item->getUdpoCustomCost()): ?>disabled="disabled"<?php endif?> />
        <input onclick="udpoToggleBaseCostInput(this)" type="checkbox" <?php if (!$_item->getUdpoCustomCost()): ?> checked<?php endif?>>
    </td>
    <?php else: ?>
    <td id="po-item-cost-<?php echo $_item->getId()?>" class="a-right po-item-cost"><?php echo $hlp->displayPrices($this->getOrder(), $_item->getUdpoBaseCost()) ?></td>
    <?php endif ?>
    <?php endif ?>
    <td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
    <td class="<?php echo $qtyLast?> a-center">
        <input type="text" class="input-text qty-input" name="udpo[items][<?php echo $_item->getId() ?>]" value="<?php echo $_item->getUdpoCreateQty()*1 ?>" />
    </td>
    <?php if ($isViewCost): ?>
    <td class="last a-right"><?php echo $hlp->displayPrices($this->getOrder(), $_item->getUdpoBaseCost()*$_item->getUdpoCreateQty()) ?></td>
    <?php endif ?>
</tr>

<script type="text/javascript">
//<![CDATA[

require(["jquery", "prototype"], function(jQuery) {
window.udpoToggleBaseCostInput = function (cbx) {
    $(cbx).previous().disabled = !$(cbx).previous().disabled;
    if ($(cbx).previous().disabled) {
        if ((new Number($(cbx).previous().value)).toFixed(2) != (new Number($(cbx).previous().alt)).toFixed(2)) {
            $(cbx).previous().value = $(cbx).previous().alt
            window.checkButtonsRelation()
        }
    }
}
});

//]]>
</script>