<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data) :?>
			<?php 
				$attributeValue = $_data['value'];
				if (is_numeric($attributeValue)) {
					$decimalDigitCount = strlen(substr(strrchr($attributeValue, "."), 1)) ? strlen(substr(strrchr($attributeValue, "."), 1)) : 0;
					if ($decimalDigitCount > 2){
						$attributeValue = number_format($attributeValue,2);
					}
				}
			?>
			<tr>
				<th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
				<td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>"><?= /* @noEscape */ $_helper->productAttribute($_product, $attributeValue, $_data['code']) ?></td>
			</tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>