<span class="contact-number dp-store-details"><a style="color:#ffffff;margin:10px;font-size:13px;" href="tel:732-510-1415">732-510-1415</a></span>
<span class="demo-tooltip dp-store-details">
    <a href="#" class="tooltip-toggle" style="color:#ffffff;font-size:13px;">Phone Support</a>
    <span class="tooltip-content">
		<strong style="font-size:15px;color:#444444;margin-bottom:10px!important;">Sales Hours</strong>
		<p style="margin-top:10px;text-transform:none!important"><strong>Mon-Fri : 9am - 5pm</strong></p>
        <strong style="font-size:15px;color:#444444;margin-bottom:10px!important;">Customer Service</strong>
		<p style="margin-top:10px;text-transform:none!important"><strong>Mon-Fri : 9am - 5pm</strong></p>
	</span>
</span>