<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
//@codingStandardsIgnoreFile
?>
<?php $helper = $block->getHelper(); ?>
<?php $popup = $block->getPopup();?>

<div class="mteo-theme-default mteo_content_<?php echo $popup->getContentType();?>"
     style="background-color: <?php echo $block->getColor(1);?>">
    <a class="mteo-popup-close mteo-close" href="#"></a>
    <?php echo $block->getChildHtml($popup->getContentType());?>
</div>
