<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
?>
<div class="checkbox-field">
<input
    name="<?php echo $block->escapeHtml($block->getName());?>"
    type="checkbox"
    data-field-name="<?php echo $block->escapeHtml($block->getLabel())?>"
    value="1"
    class="mteo-additional-field mteo-additional-field-<?php
        echo $block->escapeHtml($block->getName());
        echo $block->getIsRequire()?' mt-validator-required':'';
    ?>"
    id="mteo_additional_<?php echo $block->escapeHtml($block->getName());?>"
    data-error-message="<?php echo htmlentities($block->getJsonErrorMessage(), ENT_QUOTES, 'UTF-8'); ?>"/>
    <label for="mteo_additional_<?php echo $block->escapeHtml($block->getName());?>">
        <?php echo $block->getFrontendLabel(); ?>
    </label>
</div>