<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
?>
<?php $options = $block->getData('options');?>
<?php if (count($options) >= 2) : ?>
    <?php foreach ($options as $option) : ?>
        <div class="checkbox-field radio-field">
            <input
                name="<?php echo $block->escapeHtml($block->getName());?>"
                type="radio"
                value="<?php echo $block->escapeHtml($option);?>"
                class="mteo-additional-field mteo-additional-field-<?php
                    echo $block->escapeHtml($block->getName());
                    echo $block->getIsRequired()?' mt-validator-required':'';
                ?>"
                data-field-name="<?php echo $block->escapeHtml($block->getTitle())?>"
                id="mteo_additional_<?php echo $block->escapeHtml($block->getName());?>"
                />
            <label for="mteo_additional_<?php echo $block->escapeHtml($block->getName());?>">
                <?php echo $block->escapeHtml($option);?>
            </label>
        </div>
    <?php endforeach; ?>
<?php endif; ?>