<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
?>
<?php $helper = $block->getHelper();?>
<select
    name="<?php echo $block->escapeHtml($block->getName());?>"
    data-field-name="<?php echo $block->escapeHtml($block->getLabel())?>"
    class="mteo-additional-field mteo-additional-field-<?php
        echo $block->escapeHtml($block->getId());
        echo $block->getIsRequire()?' mt-validator-required':'';
    ?>"
    id="mteo_additional_<?php echo $block->escapeHtml($block->getId());?>">

    <option value=""><?php echo $block->escapeHtml($block->getLabel()); ?></option>
    <?php if ($options = $block->getData('optionValues')) : ?>
        <?php foreach ($options as $option) : ?>
            <option value="<?php echo $block->escapeHtml($option['value']);?>">
                <?php echo $block->escapeHtml($option['label']);?>
            </option>
        <?php endforeach;?>
    <?php endif; ?>

</select>

