<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
?>
<input
    name="<?php echo $block->escapeHtml($block->getName());?>"
    type="text"
    data-field-name="<?php echo $block->escapeHtml($block->getLabel())?>"
    value="<?php echo $block->escapeHtml($block->getLabel())?>"
    class="mteo-additional-field mteo-additional-field-<?php
    echo $block->escapeHtml($block->getId());
    echo $block->getIsRequire()?' mt-validator-required':'';?>"
    id="mteo_additional_<?php echo $block->escapeHtml($block->getId());?>"
    onclick="if(this.value=='<?php echo $block->escapeHtml($block->getLabel())?>') this.value=''"
    onblur="if(this.value=='') this.value='<?php echo $block->escapeHtml($block->getLabel())?>'"
    />