<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

use Magento\Framework\Data\Helper\PostHelper;
use Magento\Sales\Block\Order\Recent;

/** @var $block Recent */

$weSupplyHelper = $this->helper('WeSupply\Toolbox\Helper\Data');
$orderViewType = $weSupplyHelper->getOrdersViewType();
$_orders = $orderViewType !== 'ws_order_list' ? $block->getOrders() : $weSupplyHelper->getWsOrders();
$generatedOrdersLink = $orderViewType === 'ws_order_list' || $orderViewType === 'ws_order_view' ?
    $weSupplyHelper->getGenerateOrderMap($_orders, true) : false;
?>

<?php if ($weSupplyHelper->getEnableWeSupplyRecentOrders()): ?>
    <div class="block block-dashboard-orders">
        <div class="block-title order">
            <strong><?= $block->escapeHtml(__('Recent Orders')) ?></strong>
            <?php if ($_orders && count($_orders)): ?>
                <a class="action view" href="<?= $block->escapeHtml($block->getUrl('sales/order/history')) ?>">
                    <span><?= $block->escapeHtml(__('View All')) ?></span>
                </a>
            <?php endif; ?>
        </div>
        <div class="block-content">
            <?= $block->getChildHtml() ?>
            <?php if ($_orders && count($_orders)): ?>
                <div class="table-wrapper orders-recent">
                    <table class="data table table-order-items recent" id="my-orders-table">
                        <caption class="table-caption"><?= $block->escapeHtml(__('Recent Orders')) ?></caption>
                        <thead>
                        <tr>
                            <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                            <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                            <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                            <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                            <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; foreach ($_orders as $key => $_order): ?>
                            <?php if ($i > 5): continue; endif; ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?></td>
                                <?php $shippingName = $orderViewType === 'ws_order_list' ?  $_order->getShippingName() :
                                    ($_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;')
                                ?>
                                <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $shippingName ?></td>
                                <?php $formattedPrice = $orderViewType === 'ws_order_list' ? $_order->getFormattedGrandTotal() : $_order->formatPrice($_order->getGrandTotal()) ?>
                                <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= $formattedPrice ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                    <?php if (is_array($generatedOrdersLink) && array_key_exists($_order->getIncrementId(),$generatedOrdersLink)): ?>
                                        <?php if ($orderViewType !== 'ws_order_list'): ?>
                                            <?php $printableOptions = $weSupplyHelper->generateAllPrintableOptionsForOrder($_order); ?>
                                            <?php if(count($printableOptions) > 0): ?>
                                                <select class="wesupply_options" <?php echo count($printableOptions) == 1 ? 'disabled="disabled"' : ''; ?> onchange="javascript:location.href = this.value;">
                                                    <?php foreach ($printableOptions as $values): ?>
                                                        <option value="<?= $block->escapeHtml($values['url']); ?>"><?= $block->escapeHtml( __($values['label'])) ?>
                                                    <?php endforeach; ?>
                                                </select>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if (($orderViewType === 'ws_order_view' && $weSupplyHelper->orderViewModalEnabled()) || $orderViewType === 'ws_order_list'): ?>
                                            <?php $linkHtml = $this->getLayout()
                                                ->createBlock('Magento\Framework\View\Element\Template')
                                                ->setOrderLink($generatedOrdersLink[$_order->getIncrementId()])
                                                ->setTemplate('WeSupply_Toolbox::embedded/orders/view_order_link.phtml');
                                            ?>
                                            <?php echo $linkHtml->toHtml(); ?>
                                        <?php else: ?>
                                            <a href="<?= $block->escapeHtml($generatedOrdersLink[$_order->getIncrementId()]) ?>" class="action view" target="_blank">
                                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                                            </a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <a href="<?= $block->escapeHtml($block->getViewUrl($_order)) ?>" class="action view">
                                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($orderViewType !== 'ws_order_list' && $this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                    <?php $postData = $this->helper(PostHelper::class)->getPostData($block->getReorderUrl($_order)); ?>
                                        <a href="#" data-post='<?= $block->escapeHtml($postData) ?>' class="action order">
                                            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                        </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php $i++; endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <?php echo $this->getChildHtml('view_order_modal'); ?>
            <?php else: ?>
                <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
