<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
//@codingStandardsIgnoreFile
?>
<div class="fieldset-wrapper" id="field-custom-options-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="title">
            <span><?php echo $block->escapeHtml(__('Additional Fields')) ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content" id="field-custom-options-content">
        <fieldset class="fieldset">
            <div class="messages">
                <div class="message message-error" id="dynamic-price-warning" style="display: none;">
                    <div class="message-inner">
                        <div class="message-content">
                            <?php echo $block->escapeHtml(
                                __('We can\'t save custom-defined options for bundles with dynamic pricing.')
                            );?>
                        </div>
                    </div>
                </div>
            </div>

            <div id="field_options_container" class="sortable-wrapper">
                <div id="field_options_container_top"></div>
                <?php echo $block->getOptionsBoxHtml() ?>
            </div>

            <div class="actions">
                <?php echo $block->getAddButtonHtml() ?>
            </div>
        </fieldset>
    </div>
</div>

<script>
require(['eopField']);
</script>
