<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Houzz
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

$houzzRootLevel = $block->getLevel( 0 ); // parent
$houzzChildLevel = $block->getLevel( 1 );

$rootCatId = $block->getRootCategory();
$savedCatIdRootLevel = $block->getSavedCategoryData( 0 );
$savedCatIdChildLevel = $block->getSavedCategoryData( 1 );

?>
<?php if(!empty($savedCatIdChildLevel)) {
	?>
	<button onclick="window.location.href='<?php echo $block->getUrl('houzz/categories/resetmapping/',
		['id' => $this->getRequest()->getParam('id')] ); ?>'">Reset Mapping</button>
	<?php
}
?>
<script>
	require([
		"jquery",

	], function($){
		var houzz_level_0=<?php echo json_encode($houzzRootLevel);?>;
		var houzz_level_1=<?php echo json_encode($houzzChildLevel);?>;
		var houzz_saved_data_level0="<?php echo $savedCatIdRootLevel; ?>";
		var houzz_saved_data_level1="<?php echo $savedCatIdChildLevel; ?>";
		var houzz_defaultcat="<?php echo $block->getCurrentCategory(); ?>";
		setTimeout(function() {
			if(houzz_defaultcat == '2')
			{
				$('[data-index="houzz_cat_level_0"]').hide();
				$('[data-index="houzz_cat_level_1"]').hide();
				$('[data-index="houzz_category_mapping"]').children().eq(0).append('<div id="error">Houzz doesn\'t entertain uploading product on root category . Please select a Magento child category</div>')
			}
			else
			{
				$('[data-index="houzz_category_mapping"]').addClass(' _show');
				$('[data-index="houzz_category_mapping"]').children().addClass(' _show');
				if(houzz_saved_data_level0 == "")
				{
					$('[name="houzz_cat_level_0"]').prepend('<option value="" selected= selected>Please select root-category</option>');
					$('[name="houzz_cat_level_1"]').empty();
					$('[name="houzz_cat_level_1"]').prepend('<option value="">Please select Sub Category</option>');
				}
				$('[name="houzz_cat_level_0"]').change(function(){
					$('[name="houzz_cat_level_1"]').empty();
					$('[name="houzz_cat_level_1"]').append('<option value="">Please select Sub Category</option>');
					var cat_id=$('[name="houzz_cat_level_0"]').val();
					for (var key in houzz_level_1) {
						for (var subkey in houzz_level_1[key]){
							if((subkey == 'parent_cat_id') && (houzz_level_1[key][subkey] == cat_id)){
								if(houzz_saved_data_level1 == houzz_level_1[key]['path'])
								{
									$('[name="houzz_cat_level_1"]').append('<option value='+houzz_level_1[key]['path']+'selected="selected'+'>'+houzz_level_1[key]['name']+'</option>');
								} else{
									$('[name="houzz_cat_level_1"]').append('<option value='+houzz_level_1[key]['path']+'>'+houzz_level_1[key]['name']+'</option>');
								}
							}
						}
					}
				});

				// FOR SETTING SAVED VALUES AFTER SAVING THEM IN LEVEL 0
				if(houzz_saved_data_level0)
				{
					$('[name="houzz_cat_level_1"]').empty();
					for (var key in houzz_level_0) {
						for (var subkey in houzz_level_0[key]){
							if(subkey == 'parent_cat_id'){
								if(houzz_saved_data_level0 == houzz_level_0[key]['path'])
								{
									$('[name="houzz_cat_level_0"]').append('<option  selected="selected" value='+houzz_level_0[key]['path']+'>'+houzz_level_0[key]['name']+'</option>');
								} else {
									$('[name="houzz_cat_level_0"]').append('<option value='+houzz_level_0[key]['path']+'>'+houzz_level_0[key]['name']+'</option>');
								}
							}
						}
					}
				}

				// FOR SETTING SAVED VALUES AFTER SAVING THEM IN LEVEL 1
				if (houzz_saved_data_level1) {
					$('[name="houzz_cat_level_1"]').empty();
					var cat_id=$('[name="houzz_cat_level_0"]').val();
					for (var key in houzz_level_1) {
						for (var subkey in houzz_level_1[key]){
							if(subkey == 'parent_cat_id'){
								if(houzz_level_1[key][subkey] == cat_id)
								{
									if(houzz_saved_data_level1 == houzz_level_1[key]['path'])//LEVEL 1 value selection
									{
										$('[name="houzz_cat_level_1"]').append('<option  selected="selected" value='+houzz_level_1[key]['path']+'>'+houzz_level_1[key]['name']+'</option>');
									} else {
                                        $('[name="houzz_cat_level_1"]').append('<option value=' + houzz_level_1[key]['path'] + '>' + houzz_level_1[key]['name'] + '</option>');
                                    }

								}

							}
						}
					}
				}

			}
		}, 10);

	});
</script>


