<?php
/**
 * Unirgy LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.unirgy.com/LICENSE-M1.txt
 *
 * @category   Unirgy
 * @package    Unirgy_DropshipPo
 * @copyright  Copyright (c) 2008-2009 Unirgy LLC (http://www.unirgy.com)
 * @license    http:///www.unirgy.com/LICENSE-M1.txt
 */
?>
<?php $hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data') ?>
<?php $_po    = $this->getPo() ?>
<?php $_order = $this->getOrder() ?>
<?php if ($_po && $_order): ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo __('Item') ?></th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo __('Sku') ?></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo __('Cost') ?></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo __('Qty') ?></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo __('Row Cost') ?></th>
        </tr>
    </thead>

    <?php $i=0; foreach ($_po->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#eeeded"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tfoot>
        <tr>
            <td colspan="4" align="right" style="padding:3px 9px">Total Cost</td>
            <td align="right" style="padding:3px 9px"><?php echo $hlp->displayPrices($_order, $_po->getTotalCost()) ?></td>
        </tr>
    </tfoot>

</table>

<?php if($_order->getGiftMessageId() && ($_giftMessage = $hlp->getObj('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()))): ?>

<br />

<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><strong><?php echo __('Gift Message for this Order') ?></strong></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="4" align="left" style="padding:3px 9px">
            <strong><?php echo __('From:'); ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?>
            <br /><strong><?php echo __('To:'); ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?>
            <br /><strong><?php echo __('Message:'); ?></strong><br /> <?php echo $this->escapeHtml($_giftMessage->getMessage()) ?>
            </td>
        </tr>
    </tbody>
</table>

<?php endif; ?>

<?php endif; ?>
