<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
//@codingStandardsIgnoreFile
?>
<?php $helper = $block->getHelper(); ?>
<?php $popup = $block->getPopup();?>
<?php $additionalFields = $block->getAdditionalFields(); ?>
<div  id="mteo_subcription_form" class="mteo-form-with-additional">
    <?php if ($block->getText(1)) : ?>
    <div class="mteo-text-row-1" style="color: <?php echo $block->getColor(2); ?>">
        <?php echo $block->getText(1) ?>
    </div>
    <?php endif; ?>

    <?php if ($block->getText(2)) : ?>
    <div class="mteo-text-row-2" style="color: <?php echo $block->getColor(2); ?>">
        <?php echo $block->getText(2) ?>
    </div>
    <?php endif; ?>


    <div class="mteo-subscribe">
        <?php if ($block->getText(3)) : ?>
            <div class="mteo-text-row-3" style="color: <?php echo $block->getColor(2); ?>">
                <?php echo $block->getText(3) ?>
            </div>
        <?php endif; ?>
        <?php if ($additionalFields): ?>
            <?php foreach ($additionalFields as $field): ?>
                <?php if($field['after_email_field'] == 0):?>
                    <?php echo $block->getFieldHtml($field);?>
                <?php endif;?>
            <?php endforeach;?>
        <?php endif;?>
        <input class="mt-validator-required mt-validator-email" data-field-name="<?php echo $helper->translate('email'); ?>" onclick="if(this.value=='<?php echo $helper->translate('email'); ?>') this.value=''" onblur="if(this.value=='') this.value='<?php echo $helper->translate('email'); ?>'" id="mteo_email" name="subscribe_email" value="<?php echo $helper->translate('email'); ?>" type="text">

        <?php if ($additionalFields): ?>
            <?php foreach ($additionalFields as $field): ?>
                <?php if($field['after_email_field'] == 1):?>
                    <?php echo $block->getFieldHtml($field);?>
                <?php endif;?>
            <?php endforeach;?>
        <?php endif;?>

            <a style="background-color: <?php echo $block->getColor(3);  ?>; color: <?php echo $block->getColor(2); ?>" href="javascript:void(0)" id="mteo_contact_submit" ><?php echo $helper->translate('send'); ?></a>

    </div>
    <div id="mteo_msg_error" style="color: <?php echo $block->getColor(2); ?>"></div>
</div>


<div id="mteo_subscription_success">
    <div class="mteo-success-msg" style="color: <?php echo $block->getColor(2); ?>"></div>
</div>