<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
//@codingStandardsIgnoreFile
?>

<?php $helper = $block->getHelper(); ?>
<?php $popup = $block->getPopup();?>
<?php $additionalFields = $block->getAdditionalFields(); ?>

<div  id="mteo_subcription_form">
    <?php if ($block->getText(1)) : ?>
    <div class="mteo-text-row-1" style="color: <?php echo $block->getColor(2); ?>">
        <?php echo $block->getText(1) ?>
    </div>
    <?php endif; ?>

    <?php if ($block->getText(2)) : ?>
    <div class="mteo-text-row-2" style="color: <?php echo $block->getColor(2); ?>">
        <?php echo $block->getText(2) ?>
    </div>
    <?php endif; ?>

    <?php if ($block->getText(3)) : ?>
    <div class="mteo-text-row-3" style="color: <?php echo $block->getColor(2); ?>">
        <?php echo $block->getText(3) ?>
    </div>
    <?php endif; ?>

</div>


<div class="mteo_buttons">
    <a class="mteo_yes show_coupon" href="#" style="background-color: <?php echo $block->getColor(2); ?>; color: <?php echo $block->getColor(1); ?>"><?php echo $block->getText(5);?><span><?php echo $block->getText(6);?></span></a>
    <a class="mteo_no mteo-close" href="#" style="background-color: <?php echo $block->getColor(3); ?>; color: <?php echo $block->getColor(2); ?>""><?php echo $block->getText(7);?><span><?php echo $block->getText(8);?></span></a>
</div>

<div id="mteo_subscription_success_with_coupon">
    <div id="mteo_msg_success" style="color: <?php echo $block->getColor(2); ?>"><?php echo $helper->translate('coupon_getting_success_message');?></div>
    <div id="mteo_coupon">
        <div id="mteo_coupon_code" style="background-color: <?php echo $block->getColor(2);?>; border-color: <?php echo $block->getColor(3);?>"><?php echo $helper->translate('coupon');?> <span>df56s5d8</span></div>
        <div class="mteo-box-shop-now-button"><a style="color: <?php echo $block->getColor(2); ?>; background-color: <?php echo $block->getColor(3); ?>" class="mteo-close" href="#" style=""><?php echo $helper->translate('shop_now'); ?></a> </div>
    </div>
</div>
