<?php
// @codingStandardsIgnoreFile
/** @var $_helper WeltPixel\ThankYouPage\Helper\Data */
$_helper = $this->helper('WeltPixel\ThankYouPage\Helper\Data');
$pageSubtitle = $_helper->getPageSubTitle();
$_order = $block->getLastOrder();
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-page-title-wrapper thank-you-page">
    <div class="icon_thank_you_01"></div>
    <h1 class="page-title"><?= $_helper->getPageTitle() ?></h1>
</div>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __($pageSubtitle, sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __($pageSubtitle, sprintf('<strong>%s</strong>', $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php endif;?>
        <p><?= $_helper->getOrderDescription() ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <?php if ($_helper->showContinueShopping()) : ?>
        <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$collection = $objectManager->create('Magento\Sales\Model\Order');
$orderInfo = $collection->loadByIncrementId($block->getOrderId());
$orderId = $orderInfo->getId();

//$orderData=$order->load($block->getOrderId());

$billingArr = $orderInfo->getBillingAddress()->getData();

$email =  $billingArr['email'];
$fname =  $billingArr['firstname'];
$lname =  $billingArr['lastname'];
$streetAddress = $billingArr['street'];
$city = $billingArr['city'];
$state = $billingArr['region'];
$country = $billingArr['country_id'];
$postcode = $billingArr['postcode'];
$phone = $billingArr['telephone'];

?>

<div style="display:none;">
    <div class="email-gtm"><?= $email;?></div>
    <div class="fname-gtm"><?= $fname;?></div>
    <div class="lname-gtm"><?= $lname;?></div>
    <div class="streetAddress-gtm"><?= $streetAddress;?></div>
    <div class="city-gtm"><?= $city;?></div>
    <div class="state-gtm"><?= $state;?></div>
    <div class="country-gtm"><?= $country;?></div>
    <div class="postcode-gtm"><?= $postcode;?></div>
    <div class="phone-gtm"><?= $phone;?></div>
</div>

<?php
// Order object
$itemsArr = [];
foreach ($orderInfo->getAllVisibleItems() as $item) {
    $itemsArr[] = [
        'id' => $item->getSku(),
        'price' => (float) $item->getPriceInclTax(), // Use getPriceInclTax() for price with tax
        'quantity' => (int) $item->getQtyOrdered()
    ];
}
$jsonItems = json_encode($itemsArr);
//var_dump($jsonItems);
?>

<script type="text/javascript">
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    // Prepare the purchase event data
    var purchaseEventData = {
        "send_to": "AW-18093203629/AOBNCIyr8J8cEK3BwbND",
        "transaction_id": "<?= htmlspecialchars($block->escapeJs($orderInfo->getIncrementId()), ENT_QUOTES, 'UTF-8') ?>",
        "value": <?= htmlspecialchars($block->escapeJs($orderInfo->getGrandTotal()), ENT_QUOTES, 'UTF-8') ?>,
        "currency": "<?= htmlspecialchars($block->escapeJs($orderInfo->getOrderCurrencyCode()), ENT_QUOTES, 'UTF-8') ?>",
        "discount": <?= htmlspecialchars($block->escapeJs($orderInfo->getDiscountAmount()), ENT_QUOTES, 'UTF-8') ?>,
        "aw_feed_country": "<?= htmlspecialchars($block->escapeJs($country), ENT_QUOTES, 'UTF-8') ?>",
        "aw_feed_language": "EN",
        "items": <?= $jsonItems ?>
    };

    // Send the purchase event to Google Analytics 4
    gtag('event', 'purchase', purchaseEventData);

    // Log the event data to the browser console
    console.log("Sending purchase event to GA4:", purchaseEventData);
</script>