<?php
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
$_poHlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipPo\Helper\Data');
$_po = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\Registry')->registry('current_udpo');
$method = explode('_', $_po->getUdropshipMethod(), 2);
$_vendor = $_po->getVendor();
$carrierCode = !empty($method[0]) ? $method[0] : $_vendor->getCarrierCode();
$poShippingMethod = $_po->getUdropshipMethod();
if (null == $poShippingMethod) {
    $poShippingMethod = $_po->getOrder()->getShippingMethod();
}
?>

<div id="udpo_totals" class="admin__page-section-item order-totals">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Shipment Totals') ?></span>
    </div>
    <div class="admin__page-section-item-content order-totals-actions">
<div class="admin__field admin__field-option">
    <label class="normal" for="shipment_generate_label"><?php echo __('Generate Label') ?></label>
    <input id="shipment_generate_label" name="shipment[generate_label]" value="1" type="checkbox" onclick="$('shipment_generate_label_form').toggle()" />
</div>
<div id="shipment_generate_label_form" style="display:none">

<div class="admin__field admin__field-option">
    <label for="shipment_label_use_method_code"><?php echo __('Shipping Method') ?></label>
    <select id="shipment_label_use_method_code" name="shipment[label_info][use_method_code]">
        <?php foreach($_poHlp->getPoAvailableMethods($_po) as $_amCode => $_amDesc): ?>
            <option value="<?php echo $_amCode?>" <?php if ($poShippingMethod==$_amCode): ?> selected<?php endif?>><?php echo $_amDesc?></option>
        <?php endforeach ?>
    </select>
</div>
<div class="admin__field admin__field-option">
    <label for="shipment_label_weight"><?php echo __('Shipment Info')?></label>
    <?php echo __('Weight:') ?>
    <input id="shipment_label_weight" name="shipment[label_info][weight]" value="<?php echo $_po->getRemainingWeight() ?>" title="<?php echo __('Weight') ?>" type="text" class="input-text" style="width:50px;" /> LB
&nbsp;&nbsp;
    <?php echo __('Value:') ?>
    <input id="shipment_label_value" name="shipment[label_info][value]" value="<?php echo $_po->getRemainingValue() ?>" title="<?php echo __('Declared Value') ?>" type="text" class="input-text" style="width:50px;"/> <?php echo $_po->getOrder()->getStoreCurrencyCode() ?>
</div>
<div class="admin__field admin__field-option">
    <label for="shipment_label_length"><?php echo __('Pkg. Dimensions')?></label>
    <?php echo __('Length:') ?>
    <input id="shipment_label_length" name="shipment[label_info][length]" value="<?php echo (float)$_vendor->getDefaultPkgLength()?>" title="<?php echo __('Length') ?>" type="text" class="input-text" style="width:30px;" />
    &nbsp;&nbsp;
    <?php echo __('Width:') ?>
    <input id="shipment_label_width" name="shipment[label_info][width]" value="<?php echo (float)$_vendor->getDefaultPkgWidth()?>" title="<?php echo __('Width') ?>" type="text" class="input-text" style="width:30px;" />
    &nbsp;&nbsp;
    <?php echo __('Height:') ?>
    <input id="shipment_label_height" name="shipment[label_info][height]" value="<?php echo (float)$_vendor->getDefaultPkgHeight()?>" title="<?php echo __('Height') ?>" type="text" class="input-text" style="width:30px;" />
</div>
<div class="admin__field admin__field-option">
    <?php if ($carrierCode=='fedex'): ?>
    <label for="shipment_label_package_count"><?php echo __('Package Count') ?></label>
    <select id="shipment_label_package_count" name="shipment[label_info][package_count]" value="1" title="<?php echo __('Package Count') ?>">
        <?php foreach(range(1,10) as $pcIdx): ?>
            <option value="<?php echo $pcIdx?>"><?php echo $pcIdx?></option>
        <?php endforeach ?>
    </select>
    <br />
    <?php endif ?>
</div>
<div class="admin__field admin__field-option">
    <label for="shipment_label_reference"><?php echo __('Reference') ?></label>
    <input id="shipment_label_reference" name="shipment[label_info][reference]" value="<?php echo $_po->getIncrementId() ?>" title="<?php echo __('Reference') ?>" type="text" class="input-text" style="width:250px;" />
</div>
<div class="admin__field admin__field-option">
    <label for="shipment_label_use_label_shipping_amount"><?php echo __('Use Label Amount') ?></label>
    <input id="shipment_label_use_label_shipping_amount" name="shipment[use_label_shipping_amount]" value="1" title="<?php echo __('Use Label Shipping Amount') ?>" type="checkbox" class="input-checkbox" onchange="$('shipment_shipping_amount_ctr').toggle()" />
    <br />
</div>
</div>

<div id="shipment_shipping_amount_ctr" class="admin__field admin__field-option">
    <label class="normal" for="shipment_shipping_amount"><?php echo __('Shipping Amount') ?></label>
    <input id="shipment_shipping_amount" name="shipment[shipping_amount]" value="<?php echo $_po->getBaseShippingAmountLeft()?>" />
</div>

<div class="admin__field admin__field-option">
    <label class="normal" for="shipment_do_invoice"><?php echo __('Invoice Shipment') ?></label>
    <input id="shipment_do_invoice" name="shipment[do_invoice]" value="1" type="checkbox" />
</div>

<div class="admin__field admin__field-option">
    <label class="normal" for="shipment_mark_as_shipped"><?php echo __('Mark As Shipped') ?></label>
    <input id="shipment_mark_as_shipped" name="shipment[mark_as_shipped]" value="1" type="checkbox" />
</div>
    </div>
</div>

<script type="text/javascript">
require(["jquery", "prototype","domReady!"], function(jQuery) {
$$('#ship_items_container .order-totals')[0].insertBefore($('udpo-shipment-totals'), $$('#ship_items_container .order-totals')[0].childElements()[0])
});
</script>
