<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="aw-pq-menu admin__action-dropdown-wrap">
    <button class="admin__action-dropdown" title="Menu" data-toggle="dropdown" data-mage-init='{"dropdown":{}}'>
        <span class="admin__action-dropdown-text"><?php echo $this->escapeHtml($this->getCurrentItemTitle());?></span>
    </button>
    <ul class="admin__action-dropdown-menu">
        <?php foreach($this->getItems() as $key => $item):?>
            <li class="action-dropdown-menu-action<?php echo ($key==$this->getCurrentItemKey()?' current':'');?> <?php echo array_key_exists('class', $item)? $item['class']: '';?>">
                <a href="<?php echo $this->escapeUrl($item['url']);?>" data-ui-id="awpq-<?php echo (int)$key;?>" title="<?php echo $this->escapeHtml($item['title']);?>"
                    <?php echo array_key_exists('target', $item)?'target="' . $item['target'] . '"':'';?>><?php echo $this->escapeHtml($item['title']);?></a>
            </li>
        <?php endforeach;?>
    </ul>
</div>