<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/Eop
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-exit-intent-popup-extension
 */
?>
<?php if ($block->isActive() && $block->canShow()) :?>
    <?php $popup = $block->getPopup();?>
    <a
        id="esnp_button"
        class="esnp-<?php echo $block->escapeHtml($popup->getButtonPosition());?> mt-np-popup-open"
        <?php if ($popup->getButtonTop()) : ?>
        style="top: <?php echo $block->escapeHtml($popup->getButtonTop());?>"
        <?php endif;?>
        href="javascript:void(0)"
        title="<?php echo $block->escapeHtml($popup->getButtonText())?>">
            <span><?php echo $block->escapeHtml($popup->getButtonText())?></span>
    </a>
<?php endif;?>